apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: mern-app
data:
  NODE_ENV: "production"
  PORT: "5000"
  MONGO_URI: "mongodb://mongodb-service:27017/scan2win"
  FRONTEND_URL: "http://frontend-service:80"
