apiVersion: v1
kind: ConfigMap
metadata:
  name: mern-config
  namespace: {{ .Values.global.namespace }}
data:
  NODE_ENV: {{ .Values.backend.env.NODE_ENV | quote }}
  PORT: {{ .Values.backend.env.PORT | quote }}
  FRONTEND_URL: {{ .Values.backend.env.FRONTEND_URL | quote }}
  MONGO_URI: {{ .Values.backend.env.MONGO_URI | quote }}
  VITE_API_BASE_URL: {{ .Values.frontend.env.VITE_API_BASE_URL | quote }}
  VITE_FRONTEND_URL: {{ .Values.frontend.env.VITE_FRONTEND_URL | quote }}
