apiVersion: v1
kind: Secret
metadata:
  name: mern-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: {{ .Values.mongodb.auth.rootUsername | quote }}
  MONGO_ROOT_PASSWORD: {{ .Values.mongodb.auth.rootPassword | quote }}
  MONGO_DATABASE: {{ .Values.mongodb.auth.database | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  SENDGRID_API_KEY: {{ .Values.secrets.sendgridApiKey | quote }}
  MAIL_FROM: {{ .Values.secrets.mailFrom | quote }}
