{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: mongodb
    {{- include "mern-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mongodb.service.type }}
  ports:
  - port: {{ .Values.mongodb.service.port }}
    targetPort: 27017
    protocol: TCP
    name: mongodb
  selector:
    app: mongodb
{{- end }}
